name: LocalStack Benchmark
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  docker-build:
    name: Build with Docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init targets/localstack

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - name: Multi-arch build
        run: |
          cd targets/localstack
          make docker-build-multiarch

  nsc-build:
    name: Build with Namespace
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init targets/localstack

      - uses: namespacelabs/nscloud-setup@v0

      - uses: namespacelabs/nscloud-setup-buildx-action@v0

      - name: Multi-arch build
        run: |
          cd targets/localstack
          make docker-build-multiarch
