name: PostHog Benchmark
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  nsc-build:
    name: Build with Namespace
    runs-on: 
      - nscloud-ubuntu-22.04-amd64-8x16-with-cache
      - nscloud-git-mirror-10gb
    timeout-minutes: 30
    steps:
      - uses: namespacelabs/nscloud-checkout-action@HEAD
        with:
          submodules: true

      - run: |
          ls
          git status
          git log -2
      - uses: namespacelabs/nscloud-setup@v0

      - uses: namespacelabs/nscloud-setup-buildx-action@v0

      - uses: docker/build-push-action@v4
        with:
          context: ./posthog
