name: PostHog Benchmark
on:
  push:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  nsc-build:
    name: Build with Namespace
    runs-on: 
      - nscloud-ubuntu-22.04-amd64-8x16-with-cache
      - nscloud-git-mirror-20gb
    timeout-minutes: 30
    steps:
      - uses: namespacelabs/nscloud-checkout-action@HEAD
      # - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_CHECKOUT_PAT }}
          fetch-depth: 2

      - run: |
          sudo apt-get install -y tree
          ls
          ls posthog
          ls ClickHouse
          git status
          git log -10
          git submodule status
          tree .
      - uses: namespacelabs/nscloud-setup@v0

      - uses: namespacelabs/nscloud-setup-buildx-action@v0

      - uses: docker/build-push-action@v4
        with:
          context: ./posthog
