name: LocalStack Benchmark
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  docker-build:
    name: Build with Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init targets/novu

      - uses: docker/setup-buildx-action@v2

      - run: make docker-build-multiarch

  nsc-build:
    name: Build with Namespace
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init targets/novu

      - uses: namespacelabs/nscloud-setup@v0

      - uses: namespacelabs/nscloud-setup-buildx-action@v0

      - run: make docker-build-multiarch
