name: LocalStack Benchmark
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  docker-build:
    name: Build with Docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init targets/localstack

      - uses: docker/setup-buildx-action@v2

      - name: Docker build
        run: |
          cd targets/localstack
          docker buildx build \
            --cache-from localstack/localstack --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg LOCALSTACK_PRE_RELEASE=$(cat localstack/__init__.py | grep '^__version__ =' | grep -v '.dev' >> /dev/null && echo "0" || echo "1") \
            --build-arg LOCALSTACK_BUILD_GIT_HASH=$(git rev-parse --short HEAD) \
            --build-arg=LOCALSTACK_BUILD_DATE=$(date -u +"%Y-%m-%d") \
            --build-arg=LOCALSTACK_BUILD_VERSION=$(cat localstack/__init__.py | grep '^__version__ =' | sed "s/__version__ = ['\"]\(.*\)['\"].*/\1/") \
            --add-host="localhost.localdomain:127.0.0.1" \
            -t localstack/localstack . -f ./Dockerfile

  nsc-build:
    name: Build with Namespace
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: git submodule update --init targets/localstack

      - uses: namespacelabs/nscloud-setup@v0

      - uses: namespacelabs/nscloud-setup-buildx-action@v0

      - name: Docker build
        run: |
          cd targets/localstack
          docker buildx build \
            --build-arg LOCALSTACK_PRE_RELEASE=$(cat localstack/__init__.py | grep '^__version__ =' | grep -v '.dev' >> /dev/null && echo "0" || echo "1") \
            --build-arg LOCALSTACK_BUILD_GIT_HASH=$(git rev-parse --short HEAD) \
            --build-arg=LOCALSTACK_BUILD_DATE=$(date -u +"%Y-%m-%d") \
            --build-arg=LOCALSTACK_BUILD_VERSION=$(cat localstack/__init__.py | grep '^__version__ =' | sed "s/__version__ = ['\"]\(.*\)['\"].*/\1/") \
            --add-host="localhost.localdomain:127.0.0.1" \
            -t localstack/localstack . -f ./Dockerfile
